ingressHost: chart-pact-broker.service.core-compute-preview.internal
databaseType: pod

postgresql:
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: hmcts
  persistence:
    enabled: false