---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- ( include "labels" . ) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- ( include "labels" . ) | indent 8 }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Release.Name }}
        env:
          - name: PACT_BROKER_DATABASE_HOST
            value: {{ .Release.Name }}-postgresql 
          - name: PACT_BROKER_DATABASE_USERNAME
            value: {{ .Values.postgresql.postgresqlUsername }}
          - name: PACT_BROKER_DATABASE_PASSWORD
            value: {{ .Values.postgresql.postgresqlPassword }}
          - name: PACT_BROKER_DATABASE_NAME
            value: {{ .Values.postgresql.postgresqlDatabase }}
          - name: PACT_BROKER_DISABLE_SSL_VERIFICATION
            value: 'true'
          - name: PACT_BROKER_PUBLIC_HEARTBEAT
            value: 'true'
          - name: PACT_BROKER_LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            memory: {{ .Values.memoryRequests }}
            cpu: {{ .Values.cpuRequests }}
          limits:
            memory: {{ .Values.memoryLimits }}
            cpu: {{ .Values.cpuLimits }}
        ports:
        - containerPort: {{ .Values.applicationPort }}
          name: http
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessPath }}
            port: {{ .Values.applicationPort }}
          initialDelaySeconds: {{ .Values.livenessDelay }}
          timeoutSeconds: {{ .Values.livenessTimeout }}
          periodSeconds: {{ .Values.livenessPeriod }}
          failureThreshold: {{ .Values.livenessFailureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessPath }}
            port: {{ .Values.applicationPort }}
          initialDelaySeconds: {{ .Values.readinessDelay }}
          timeoutSeconds: {{ .Values.readinessTimeout }}
          periodSeconds: {{ .Values.readinessPeriod }}
        imagePullPolicy: IfNotPresent
