---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- ( include "labels" . ) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- ( include "labels" . ) | indent 8 }}
    spec:
      containers:
      - image: {{ required "image " .Values.image  }}
        name: {{ .Release.Name }}
        env:
          - name: PACT_BROKER_DATABASE_HOST
            value: {{ .Release.Name }}-postgresql 
          - name: PACT_BROKER_DATABASE_USERNAME
            value: {{ required "postgresql.postgresqlUsername " .Values.postgresql.postgresqlUsername  }}
          - name: PACT_BROKER_DATABASE_PASSWORD
            value: {{ required "postgresql.postgresqlPassword " .Values.postgresql.postgresqlPassword  }}
          - name: PACT_BROKER_DATABASE_NAME
            value: {{ required "postgresql.postgresqlDatabase " .Values.postgresql.postgresqlDatabase  }}
          - name: PACT_BROKER_DISABLE_SSL_VERIFICATION
            value: 'true'
          - name: PACT_BROKER_PUBLIC_HEARTBEAT
            value: 'true'
          - name: PACT_BROKER_LOG_LEVEL
            value: WARN
        resources:
          requests:
            memory: {{ required "memoryRequests " .Values.memoryRequests  }}
            cpu: {{ required "cpuRequests " .Values.cpuRequests  }}
          limits:
            memory: {{  required "memoryLimits  " .Values.memoryLimits   }}
            cpu: {{  required "cpuLimits  " .Values.cpuLimits   }}
        ports:
        - containerPort: {{ required "applicationPort " .Values.applicationPort  }}
          name: http
        livenessProbe:
          httpGet:
            path: {{ required "livenessPath" .Values.livenessPath  }}
            port: {{  required "applicationPort " .Values.applicationPort  }}
          initialDelaySeconds: {{  required "livenessDelay " .Values.livenessDelay  }}
          timeoutSeconds: {{  required "livenessTimeout " .Values.livenessTimeout  }}
          periodSeconds: {{  required "livenessPeriod " .Values.livenessPeriod  }}
          failureThreshold: {{  required "livenessFailureThreshold  " .Values.livenessFailureThreshold   }}
        readinessProbe:
          httpGet:
            path: {{ required "readinessPath" .Values.readinessPath   }}
            port: {{  required "applicationPort" .Values.applicationPort  }}
          initialDelaySeconds: {{  required "readinessDelay " .Values.readinessDelay  }}
          timeoutSeconds: {{  required "readinessTimeout " .Values.readinessTimeout  }}
          periodSeconds: {{  required "readinessPeriod " .Values.readinessPeriod  }}
        imagePullPolicy: IfNotPresent
