applicationPort: 80
memoryRequests: '512Mi'
cpuRequests: '100m'
memoryLimits: '1024Mi'
cpuLimits: '2500m'
ingressHost: pact-broker.service.core-compute-saat.internal
readinessPath: '/diagnostic/status/heartbeat'
readinessDelay: 30
readinessTimeout: 3
readinessPeriod: 15
livenessPath: '/diagnostic/status/heartbeat'
livenessDelay: 30
livenessTimeout: 3
livenessPeriod: 15
livenessFailureThreshold: 3

databaseType: external   # external, pod, osba
resourceGroup: pact-broker-sandbox-mgmt   # osba only
postgresqlPlan: general-purpose   # osba only
